stages:
  - build
  - lint
  - test

build_backend:
  image: continuumio/miniconda3
  stage: build
  script:
    - cd ./backend
    - source activate super
    - conda env update -f environment.yml
    - echo 'conda install ok'

build_wx:
  stage: build
  script:
    - cd ./wxFrontend
    - npm install

build_admin:
  stage: build
  script:
    - cd ./adminFrontend
    - npm install

lint_admin:
  stage: lint
  script:
    - cd ./adminFrontend
    - npm run lint

lint_wx:
  stage: lint
  script:
    - cd ./wxFrontend
    - npm run lint

lint_backend:
  stage: lint
  script:
    - cd ./backend
    - source activate super
    - pylint --disable=R,C --load-plugins pylint_django backend vron

test_backend:
  stage: test
  script:
    - cd ./backend
    - source activate super
    - python ./manage.py test vron

test_wx:
  stage: test
  script:
    - cd ./wxFrontend
    - npm run test
