stages:
  - build
  - lint
  - test

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - wxFrontend/node_modules/
    - adminFrontend/node_modules/

lint_admin:
  stage: lint
  before_script:
    - cd ./adminFrontend
    - npm install
  script:
    - npm run lint

lint_wx:
  stage: lint
  before_script:
    - cd ./wxFrontend
    - npm install
  script:
    - npm run lint

lint_backend:
  stage: lint
  script:
    - cd ./backend
    - source activate super
    - pylint --disable=R,C --load-plugins pylint_django backend vron

test_backend:
  stage: test
  script:
    - cd ./backend
    - source activate super
    - python ./manage.py test vron

test_wx:
  stage: test
  before_script:
    - cd ./wxFrontend
    - npm install
  script:
    - npm run test
