channels:
  - conda-forge
  - defaults
dependencies:
  - astroid=1.6.5
  - bzip2=1.0.6
  - ca-certificates=2018.4.16
  - certifi=2018.4.16
  - django=2.1
  - djangorestframework=3.8.2
  - isort=4.3.4
  - lazy-object-proxy=1.3.1
  - mccabe=0.6.1
  - openssl=1.0.2o
  - pip=18.0
  - pylint=1.9.2
  - python=3.6.6
  - pytz=2018.5
  - setuptools=40.0.0
  - six=1.11.0
  - sqlite=3.24.0
  - tk=8.6.8
  - wheel=0.31.1
  - wrapt=1.10.11
  - xz=5.2.4
  - zlib=1.2.11
  - mysql-connector-c=6.1.11
  - mysqlclient=1.3.13
  - pip:
    - django-cors-headers
    - pylint-django
