# Generated by Django 2.1 on 2018-08-13 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='latest_read_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 16, 47, 42, 725429)),
        ),
    ]
