# Generated by Django 2.1 on 2018-08-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('key', models.CharField(max_length=18)),
            ],
        ),
    ]
