# Generated by Django 2.1 on 2018-08-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vron', '0002_activekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.CharField(default='static/upload/default_avatar.jpg', max_length=255),
        ),
    ]
