# Generated by Django 2.1 on 2018-08-17 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vron', '0002_auto_20180814_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='audio',
        ),
    ]
