# Generated by Django 2.1 on 2018-08-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vron', '0003_auto_20180824_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
    ]
