# Generated by Django 2.1 on 2018-08-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vron', '0003_remove_word_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='images',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='homework',
            name='videos',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
