# Generated by Django 2.1 on 2018-08-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vron', '0004_auto_20180826_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accept_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
