# Generated by Django 2.1 on 2018-08-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vron', '0004_auto_20180817_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='audios',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
