# Generated by Django 2.1 on 2018-08-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vron', '0005_student_accept_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClozeGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=256)),
                ('correct_word', models.CharField(max_length=64)),
                ('wrong_word_1', models.CharField(max_length=64)),
                ('wrong_word_2', models.CharField(max_length=64)),
                ('wrong_word_3', models.CharField(max_length=64)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vron.Book')),
            ],
        ),
        migrations.CreateModel(
            name='JigsawGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=256)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vron.Book')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=256)),
                ('word', models.CharField(max_length=64)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vron.Book')),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=256)),
                ('correct_word', models.CharField(max_length=64)),
                ('wrong_word_1', models.CharField(max_length=64)),
                ('wrong_word_2', models.CharField(max_length=64)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vron.Book')),
            ],
        ),
    ]
