# Generated by Django 2.1 on 2018-08-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vron', '0005_homework_audios'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nickname',
            field=models.CharField(default='', max_length=24),
        ),
    ]
